# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='coursesTaken',
            new_name='coursesToTake',
        ),
    ]
