# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_savedcourses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='savedCourses',
            new_name='saved_courses',
        ),
    ]
