# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0002_auto_20161031_0948'),
        ('profiles', '0005_auto_20161117_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_courses',
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_courses',
            field=models.ManyToManyField(to='utsida.AbroadCourse'),
        ),
    ]
