# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbroadCourse',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyPeriod', models.IntegerField()),
                ('language', models.CharField(max_length=30)),
                ('academicQualityRating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('specialCompetencyRating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('socialQualityRating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('careerAdvantagesRating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abroadCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.AbroadCourse')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('acronym', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCourse',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description_url', models.URLField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('acronym', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursesTaken', models.ManyToManyField(to='utsida.HomeCourse')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utsida.Institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='coursematch',
            name='homeCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.HomeCourse'),
        ),
        migrations.AddField(
            model_name='case',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.Country'),
        ),
        migrations.AddField(
            model_name='case',
            name='homeInstitute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.Institute'),
        ),
        migrations.AddField(
            model_name='case',
            name='subjects',
            field=models.ManyToManyField(to='utsida.AbroadCourse'),
        ),
        migrations.AddField(
            model_name='case',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.University'),
        ),
        migrations.AddField(
            model_name='abroadcourse',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.University'),
        ),
    ]
