# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyPeriod', models.IntegerField()),
                ('language', models.CharField(max_length=30)),
                ('academicQualityRating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('specialCompetencyRating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('socialQualityRating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('careerAdvantagesRating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.Country'),
        ),
        migrations.AddField(
            model_name='case',
            name='homeInstitute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.Institute'),
        ),
        migrations.AddField(
            model_name='case',
            name='subjects',
            field=models.ManyToManyField(to='utsida.Course'),
        ),
        migrations.AddField(
            model_name='case',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.University'),
        ),
    ]
