# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abroadcourse',
            name='description_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='abroadcourse',
            name='pre_requisites',
            field=models.ManyToManyField(blank=True, related_name='_abroadcourse_pre_requisites_+', to='utsida.AbroadCourse'),
        ),
    ]
