# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utsida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=400)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Disapproved')], default='P', max_length=2)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coursematch',
            unique_together=set([('homeCourse', 'abroadCourse')]),
        ),
        migrations.AddField(
            model_name='application',
            name='course_matches',
            field=models.ManyToManyField(to='utsida.CourseMatch'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
