# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='acronym',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.ForeignKey(blank=True, default='Australia', on_delete=django.db.models.deletion.CASCADE, to='utsida.Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
