# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abroadcourse',
            name='pre_requisites',
            field=models.ManyToManyField(related_name='_abroadcourse_pre_requisites_+', to='utsida.AbroadCourse'),
        ),
        migrations.AddField(
            model_name='coursematch',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursematch',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
