# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursematch',
            unique_together=set([('homeCourse', 'abroadCourse')]),
        ),
    ]
