# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0002_auto_20160928_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbroadCourse',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.University')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abroadCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.AbroadCourse')),
            ],
        ),
        migrations.CreateModel(
            name='HomeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description_url', models.URLField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterField(
            model_name='case',
            name='subjects',
            field=models.ManyToManyField(to='utsida.AbroadCourse'),
        ),
        migrations.AddField(
            model_name='coursematch',
            name='homeCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsida.HomeCourse'),
        ),
    ]
