# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 12:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0002_auto_20170228_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abroadcourse',
            name='description_url',
            field=models.URLField(blank=True, max_length=2000, validators=[django.core.validators.URLValidator]),
        ),
    ]
