# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0002_auto_20161006_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abroadcourse',
            name='description_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='homecourse',
            name='description_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
