# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utsida', '0003_auto_20170228_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='documentLink',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='coursematch',
            name='reviewer',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
