# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0003_auto_20161006_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='abroadcourse',
            name='study_points',
            field=models.FloatField(blank=True, default=7.5),
        ),
        migrations.AddField(
            model_name='coursematch',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
