# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0003_auto_20170127_1359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abroadcourse',
            unique_together=set([('code', 'name', 'university')]),
        ),
    ]
