# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0004_auto_20161011_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='abroadcourse',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abroadcourse',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='abroadcourse',
            unique_together=set([('code', 'university')]),
        ),
    ]
