# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0004_auto_20161206_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_match_application',
            old_name='shirt_size',
            new_name='status',
        ),
    ]
