# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-30 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0004_auto_20170127_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abroadcourse',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
