# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0004_auto_20170320_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematch',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
