# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0005_auto_20170320_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematch',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
