# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0005_auto_20161005_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'universities',
            },
        ),
    ]
