# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-24 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsida', '0006_auto_20170320_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='university',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='query',
            name='university',
            field=models.CharField(max_length=100),
        ),
    ]
